spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=TakivivuAuthSecretKeyForJwtMustBeAtLeast32CharactersLong2026
app.jwt.expiration-ms=3600000

auth.internal-token=TAKIVIVU_AUTH_INTERNAL_2026
service.notification.url=http://localhost:8089
notification.internal-token=TAKIVIVU_NOTIFICATION_INTERNAL_2026

# Provider business-license image upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
app.upload.provider-license-dir=uploads/provider-licenses

# =========================
# PASSWORD RESET - TAKIVIVU
# =========================

# Frontend reset password
auth.reset.frontend-url=http://localhost:5173/reset-password

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhom9qlksan@gmail.com
spring.mail.password=qdybawjhpbnakqwc

# SMTP authentication
spring.mail.properties.mail.smtp.auth=true

# TLS
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Timeout
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Encoding
spring.mail.default-encoding=UTF-8
