import {useEffect,useMemo,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {BedDouble,UsersRound,Maximize2,MapPin,Check,DoorOpen,ChevronLeft,ChevronRight} from 'lucide-react'
import {hotelApi,type PhysicalRoomInventory} from '../../api/services'
import type {Hotel,Room} from '../../types'
import {apiError,money} from '../../utils/format'
import {ErrorState,Loading} from '../../components/UI'
import './hotelRoomSelection.css'

export default function HotelRoomTypeDetailPage(){
 const {id,roomId}=useParams();const [sp,setSp]=useSearchParams();const [hotel,setHotel]=useState<Hotel|null>(null);const [room,setRoom]=useState<Room|null>(null);const [inventory,setInventory]=useState<PhysicalRoomInventory[]>([]);const [floorFilter,setFloorFilter]=useState('ALL');const [statusFilter,setStatusFilter]=useState('ALL');const [selected,setSelected]=useState<PhysicalRoomInventory|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [inventoryError,setInventoryError]=useState('');const [photoIndex,setPhotoIndex]=useState(0);const [tab,setTab]=useState<'overview'|'amenities'|'policy'|'reviews'>('overview')
 const query=sp.toString(),suffix=query?'?'+query:'';const start=sp.get('checkIn')||'',end=sp.get('checkOut')||'',guests=sp.get('guests')||'2';const hasDates=Boolean(start&&end&&new Date(end)>new Date(start));
 useEffect(()=>{let live=true;setLoading(true);setSelected(null);Promise.all([hotelApi.detail(Number(id)),hotelApi.room(Number(roomId))]).then(([h,r])=>{if(r.khachSanId!==h.id)throw Error('Loại phòng không thuộc khách sạn này.');if(live){setHotel(h);setRoom(r);setError('')}}).catch(e=>{if(live)setError(apiError(e))}).finally(()=>{if(live)setLoading(false)});hotelApi.physicalInventory(Number(id),hasDates?start:undefined,hasDates?end:undefined).then(all=>{if(live){setInventory(all.filter(r=>r.loaiPhongId===Number(roomId)));setSelected(null);setInventoryError('')}}).catch(()=>{if(live){setInventory([]);setInventoryError('Không tải được trạng thái phòng. Vui lòng thử lại.')}});return()=>{live=false}},[id,roomId,start,end])
 const rSort=(a:PhysicalRoomInventory,b:PhysicalRoomInventory)=>a.tang-b.tang||String(a.soPhong).localeCompare(String(b.soPhong),undefined,{numeric:true});const floors=useMemo(()=>[...new Set(inventory.map(r=>r.tang))].sort((a,b)=>a-b),[inventory]);const statusOf=(r:PhysicalRoomInventory)=>r.trangThai==='AVAILABLE'&&r.coTheDatTheoNgay?'AVAILABLE':r.trangThai==='BOOKED'?'BOOKED':'UNAVAILABLE';const filteredRooms=useMemo(()=>inventory.filter(r=>(floorFilter==='ALL'||String(r.tang)===floorFilter)&&(statusFilter==='ALL'||statusOf(r)===statusFilter)).sort(rSort),[inventory,floorFilter,statusFilter]);const available=inventory.filter(r=>hasDates&&r.trangThai==='AVAILABLE'&&r.coTheDatTheoNgay);const nights=hasDates?Math.ceil((new Date(end).getTime()-new Date(start).getTime())/86400000):1;const mapUrl=`/hotels/${id}/rooms-map${suffix}${suffix?'&':'?'}roomTypeId=${roomId}`;
 if(loading)return <div className="container pad"><Loading/></div>;if(error||!hotel||!room)return <div className="container pad"><ErrorState message={error||'Không tìm thấy loại phòng'}/></div>;
 const typeInfo=inventory[0];const amenities=(typeInfo?.tienNghi||'').split(',').map(x=>x.trim()).filter(Boolean);const images=[typeInfo?.hinhAnh,...(room.anhThuVien||'').split(','),...inventory.map(v=>v.hinhAnh)].map(v=>(v||'').trim()).filter((v,i,a)=>Boolean(v)&&a.indexOf(v)===i);const currentPhoto=images[Math.min(photoIndex,Math.max(0,images.length-1))];
 const pick=(r:PhysicalRoomInventory)=>{if(!hasDates||statusOf(r)!=='AVAILABLE')return;setSelected(prev=>prev?.id===r.id?null:r)};
 const setDate=(key:'checkIn'|'checkOut',value:string)=>{const next=new URLSearchParams(sp);if(value)next.set(key,value);else next.delete(key);setSp(next)};
 const stars='★'.repeat(Math.max(0,Math.min(5,Number(hotel.soSao)||0)));
 return <div className="customer-page hr-page hr-room-reference"><div className="container">
  <div className="hr-crumb"><Link to="/">Trang chủ</Link> › <Link to="/hotels">Khách sạn</Link> › <Link to={`/hotels/${id}${suffix}`}>{hotel.tenKhachSan}</Link> › {room.tenLoaiPhong}</div>
  <div className="hr-columns"><main>
   <section className="hr-room-hero">
    <h1>{room.tenLoaiPhong}</h1><div className="hr-room-hotel-line"><strong>{hotel.tenKhachSan}</strong>{stars&&<span className="hr-stars">{stars}</span>}<span><UsersRound/> Tối đa {room.sucChua} khách</span><span><MapPin/> {hotel.diaChi||hotel.thanhPho}</span></div>
    <div className="hr-room-gallery-main">{currentPhoto?<img src={currentPhoto} alt={room.tenLoaiPhong}/>:<div className="hr-no-room-photo">Chưa cập nhật ảnh loại phòng</div>}{images.length>1&&<><button type="button" className="prev" onClick={()=>setPhotoIndex(i=>(i-1+images.length)%images.length)}><ChevronLeft/></button><button type="button" className="next" onClick={()=>setPhotoIndex(i=>(i+1)%images.length)}><ChevronRight/></button><span className="counter">{photoIndex+1}/{images.length}</span></>}</div>
    {images.length>1&&<div className="hr-room-thumbs">{images.slice(0,5).map((src,i)=><button type="button" key={src} className={i===photoIndex?'active':''} onClick={()=>setPhotoIndex(i)}><img src={src} alt={`Ảnh phòng ${i+1}`}/></button>)}</div>}
    <div className="hr-room-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Tổng quan</button><button className={tab==='amenities'?'active':''} onClick={()=>setTab('amenities')}>Tiện nghi</button><button className={tab==='policy'?'active':''} onClick={()=>setTab('policy')}>Chính sách</button><button className={tab==='reviews'?'active':''} onClick={()=>setTab('reviews')}>Đánh giá</button></div>
   </section>
   <section className="hr-card hr-room-tab-content">{tab==='overview'&&<><h2>Giới thiệu phòng</h2><p>{room.moTa||'Nhà cung cấp chưa cập nhật mô tả loại phòng.'}</p><div className="hr-room-facts"><span><UsersRound/> Tối đa {room.sucChua} khách</span><span><BedDouble/> {room.tenLoaiPhong}</span><span><Maximize2/> Loại phòng</span></div></>}{tab==='amenities'&&<><h2>Tiện nghi phòng</h2><div className="hr-tags">{amenities.length?amenities.map(t=><span key={t}><Check/> {t}</span>):<span className="hr-muted">Nhà cung cấp chưa cập nhật tiện nghi.</span>}</div></>}{tab==='policy'&&<><h2>Chính sách phòng</h2><p className="hr-muted">Thông tin chính sách được áp dụng theo quy định của khách sạn.</p></>}{tab==='reviews'&&<><h2>Đánh giá</h2><p className="hr-muted">Chưa có dữ liệu đánh giá riêng cho loại phòng này.</p></>}</section>
   <section className="hr-card hr-floor-section"><div className="hr-plan-head"><h2>Danh sách phòng thuộc loại {room.tenLoaiPhong}</h2></div>{inventoryError&&<p role="alert">{inventoryError}</p>}
    <div className="hr-room-filters hr-room-filters-final"><label>Ngày nhận phòng<input type="date" value={start} onChange={e=>setDate('checkIn',e.target.value)}/></label><label>Ngày trả phòng<input type="date" min={start||undefined} value={end} onChange={e=>setDate('checkOut',e.target.value)}/></label><label>Tầng<select value={floorFilter} onChange={e=>setFloorFilter(e.target.value)}><option value="ALL">Tất cả tầng</option>{floors.map(f=><option key={f} value={String(f)}>Tầng {f}</option>)}</select></label><label>Trạng thái<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">Tất cả trạng thái</option><option value="AVAILABLE">Còn trống</option><option value="BOOKED">Đã đặt</option><option value="UNAVAILABLE">Không khả dụng</option></select></label><div className="hr-filter-count">Hiển thị <b>{filteredRooms.length}</b>/{inventory.length} phòng</div></div>
    {!hasDates&&<p className="hr-muted">Chọn ngày nhận và ngày trả phòng để kiểm tra phòng còn trống.</p>}
    <div className="hr-room-grid">{filteredRooms.map(r=>{const st=statusOf(r),canPick=hasDates&&st==='AVAILABLE',isSelected=selected?.id===r.id;return <article key={r.id} role={canPick?'button':undefined} tabIndex={canPick?0:-1} aria-pressed={canPick?isSelected:undefined} onClick={()=>pick(r)} onKeyDown={e=>{if(canPick&&(e.key==='Enter'||e.key===' ')){e.preventDefault();pick(r)}}} className={`hr-physical-card hr-click-room ${st.toLowerCase()} ${isSelected?'selected':''} ${!canPick?'disabled':''}`}><div className="hr-physical-room-icon"><DoorOpen/></div><div><h3>Phòng {r.soPhong}</h3><p>Tầng {r.tang}</p><strong>{money(Number(r.giaMoiDem))} <small>/ đêm</small></strong></div><span className={`hr-physical-status ${st.toLowerCase()}`}>{isSelected?'Đã chọn':st==='AVAILABLE'?'Còn trống':st==='BOOKED'?'Đã đặt':'Không khả dụng'}</span></article>})}{!filteredRooms.length&&<div className="hr-room-empty">Không có phòng phù hợp với bộ lọc.</div>}</div>
   </section>
  </main>
  <aside className="hr-card hr-aside hr-type-price-card"><small>Giá phòng từ</small><h2 className="hr-red">{money(Number(room.giaMoiDem))}</h2><p>/ đêm</p><div className="hr-muted">Số phòng trống thuộc loại này<br/><b>{hasDates?available.length:'Chưa chọn ngày'} {hasDates?'phòng':''}</b></div><hr/><h3>Thông tin phòng đang chọn</h3><div className="hr-selected-info" aria-label="Thông tin phòng đang chọn"><div><span>Số phòng</span><strong>{selected?.soPhong??'-'}</strong></div><div><span>Tầng</span><strong>{selected?.tang??'-'}</strong></div><div><span>Giá/đêm</span><strong>{selected?money(Number(selected.giaMoiDem)):'-'}</strong></div><div><span>Trạng thái</span><strong>{selected?'Trống':'-'}</strong></div></div>{selected&&<p className="hr-muted">{start} → {end} · {nights} đêm · {guests} khách</p>}<Link className={`hr-primary ${!selected?'hr-disabled':''}`} aria-disabled={!selected} onClick={e=>{if(!selected)e.preventDefault()}} to={selected?`/booking/new?type=HOTEL&id=${room.id}&physicalRoomId=${selected.id}&qty=1&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}&guests=${encodeURIComponent(guests)}`:'#'}>Chọn phòng →</Link>{selected&&<p className="hr-booking-note">Phòng {selected.soPhong} sẽ được kiểm tra và giữ khi xác nhận đặt phòng.</p>}<Link className="hr-secondary" to={mapUrl}>Chọn loại phòng khác →</Link><p className="hr-muted">Vui lòng chọn một phòng cụ thể để tiếp tục đặt phòng.</p></aside>
  </div>
 </div></div>
}
