import {useEffect,useMemo,useState} from 'react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {BedDouble,CalendarDays,MapPin,UsersRound,Waves,UtensilsCrossed,ShieldCheck,ArrowRight,Building2} from 'lucide-react'
import {hotelApi,type PhysicalRoomInventory} from '../../api/services'
import type {Hotel} from '../../types'
import {apiError,money} from '../../utils/format'
import {ErrorState,Loading} from '../../components/UI'
import './hotelRoomSelection.css'

export default function HotelRoomMapPage(){
 const {id}=useParams();const [sp,setSp]=useSearchParams();const query=sp.toString();
 const start=sp.get('checkIn')||'',end=sp.get('checkOut')||'',guests=sp.get('guests')||'2';
 const updateSearch=(key:string,value:string)=>{const next=new URLSearchParams(sp);if(value)next.set(key,value);else next.delete(key);setSp(next,{replace:true})};
 const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
 const validDates=!!start&&!!end&&start>=today&&end>start;
 const nights=validDates?Math.ceil((new Date(end).getTime()-new Date(start).getTime())/86400000):0;
 const [hotel,setHotel]=useState<Hotel|null>(null),[inventory,setInventory]=useState<PhysicalRoomInventory[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [floor,setFloor]=useState<number|null>(null),[typeFilter,setTypeFilter]=useState(Number(sp.get('roomTypeId')||0)),[maxPrice,setMaxPrice]=useState<number|null>(null),[chosen,setChosen]=useState<PhysicalRoomInventory[]>([]);
 useEffect(()=>setMaxPrice(null),[id]);
 useEffect(()=>{let active=true;setLoading(true);setError('');setChosen([]);Promise.all([hotelApi.detail(Number(id),validDates?start:undefined,validDates?end:undefined,Number(guests)),hotelApi.physicalInventory(Number(id),validDates?start:undefined,validDates?end:undefined)]).then(([h,rooms])=>{if(active){setHotel(h);setInventory(rooms)}}).catch(e=>{if(active)setError(apiError(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id,start,end,guests,validDates]);
 const floors=useMemo(()=>[...new Set(inventory.map(r=>r.tang))].sort((a,b)=>a-b),[inventory]);const currentFloor=floor!==null&&floors.includes(floor)?floor:floors[0];
 const types=useMemo(()=>[...new Map(inventory.map(r=>[r.loaiPhongId,r.tenLoaiPhong] as const)).entries()],[inventory]);
 const priceCeiling=useMemo(()=>Math.max(1000000,Math.ceil(Math.max(0,...inventory.map(r=>Number(r.giaMoiDem)||0))/1000000)*1000000),[inventory]);
 const effectiveMaxPrice=maxPrice===null?priceCeiling:Math.min(maxPrice,priceCeiling);
 const effectiveTypeFilter=typeFilter&&types.some(([typeId])=>typeId===typeFilter)?typeFilter:0;
 const floorRooms=inventory.filter(r=>r.tang===currentFloor);
 const matchingType=floorRooms.filter(r=>!effectiveTypeFilter||r.loaiPhongId===effectiveTypeFilter);
 const visible=matchingType.filter(r=>Number(r.giaMoiDem)<=effectiveMaxPrice).sort((a,b)=>String(a.soPhong).localeCompare(String(b.soPhong),undefined,{numeric:true}));
 const available=(r:PhysicalRoomInventory)=>validDates&&r.trangThai==='AVAILABLE'&&r.coTheDatTheoNgay;
 const toggle=(r:PhysicalRoomInventory)=>{if(!available(r))return;setChosen(old=>old.some(x=>x.id===r.id)?old.filter(x=>x.id!==r.id):[...old,r])};
 const total=chosen.reduce((sum,r)=>sum+Number(r.giaMoiDem)*nights,0);
 const typeIndex=(r:PhysicalRoomInventory)=>Math.max(0,types.findIndex(([key])=>key===r.loaiPhongId))%4;
 const status=(r:PhysicalRoomInventory)=>r.trangThai==='BOOKED'||(validDates&&r.trangThai==='AVAILABLE'&&!r.coTheDatTheoNgay)?'Đã đặt':r.trangThai==='INACTIVE'?'Bảo trì':r.trangThai==='UNVERIFIED'||!validDates?'Chưa xác minh':'Trống';
 const statusClass=(r:PhysicalRoomInventory)=>r.trangThai==='BOOKED'||(validDates&&r.trangThai==='AVAILABLE'&&!r.coTheDatTheoNgay)?'booked':r.trangThai==='INACTIVE'?'maintenance':!available(r)?'unverified':'free';
 const bookingLink=()=>`/booking/new?${new URLSearchParams({type:'HOTEL',id:String(chosen[0].loaiPhongId),physicalRoomIds:chosen.map(r=>`${r.loaiPhongId}:${r.id}`).join(','),qty:String(chosen.length),start,end,guests}).toString()}`;
 if(loading)return <div className="container pad"><Loading/></div>;if(error||!hotel)return <div className="container pad"><ErrorState message={error||'Không tìm thấy khách sạn'}/></div>;
 const hotelPhoto=hotel.hinhAnh||inventory.find(r=>r.hinhAnh)?.hinhAnh||'';
 return <div className="customer-page hr-page hr-map-reference"><div className="container">
 <div className="hr-crumb"><Link to="/">Trang chủ</Link> › <Link to="/hotels">Khách sạn</Link> › <Link to={`/hotels/${id}?${query}`}>{hotel.tenKhachSan}</Link> › Chọn phòng</div>
 <section className="hr-card hr-hotel-banner"><div className="hr-hotel-summary">{hotelPhoto&&<img src={hotelPhoto} alt={hotel.tenKhachSan}/>}<div><h2>{hotel.tenKhachSan} <span style={{color:'#f5a000'}}>{'★'.repeat(Math.min(5,Math.max(0,Number(hotel.soSao)||0)))}</span></h2><p><MapPin size={16}/> {hotel.diaChi}, {hotel.thanhPho}</p><p className="hr-hotel-amenities"><Waves size={16}/> {hotel.tienNghi||'Tiện nghi khách sạn'} <UtensilsCrossed size={16}/></p><p>{hotel.moTa}</p></div></div><div className="hr-search-summary hr-edit-dates"><label><span><CalendarDays size={16}/> Nhận phòng</span><input aria-label="Ngày nhận phòng" type="date" min={today} value={start} onChange={e=>updateSearch('checkIn',e.target.value)}/></label><label><span><CalendarDays size={16}/> Trả phòng</span><input aria-label="Ngày trả phòng" type="date" min={start>today?start:today} value={end} onChange={e=>updateSearch('checkOut',e.target.value)}/></label><label><span><UsersRound size={16}/> Số khách</span><input aria-label="Số khách" type="number" min={1} max={30} value={guests} onChange={e=>updateSearch('guests',e.target.value)}/></label></div></section>
 <div className="hr-columns"><main><div className="hr-plan-heading"><div><h1>Sơ đồ phòng khách sạn</h1><p>Chọn phòng phù hợp với nhu cầu của bạn</p></div><div className="hr-map-legend"><span><i className="hr-swatch free"/> Phòng trống</span><span><i className="hr-swatch booked"/> Đã đặt</span><span><i className="hr-swatch maintenance"/> Đang bảo trì</span></div></div>
 <div className="hr-map-filters"><label>Loại phòng<select value={effectiveTypeFilter} onChange={e=>setTypeFilter(Number(e.target.value))}><option value={0}>Tất cả loại phòng</option>{types.map(([typeId,name])=><option value={typeId} key={typeId}>{name}</option>)}</select></label><label>Tầng<select value={floor??''} onChange={e=>setFloor(e.target.value===''?null:Number(e.target.value))}><option value="">Tất cả tầng</option>{floors.map(f=><option value={f} key={f}>Tầng {f}</option>)}</select></label><label className="hr-price-filter">Giá phòng (đêm)<input type="range" min={0} max={priceCeiling} step={100000} value={effectiveMaxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><span>0 VNĐ <b>{money(effectiveMaxPrice)}</b></span></label></div>
 <section className="hr-card hr-map-floor"><div className="hr-floors">{floors.map(f=><button key={f} className={f===currentFloor?'active':''} onClick={()=>setFloor(f)}>Tầng {f}</button>)}</div><h2>Tầng {currentFloor??'—'}</h2>
 <p className="hr-muted" role="status">{floors.length===0?'Khách sạn chưa thiết lập phòng cụ thể để hiển thị sơ đồ.':`Đang hiển thị ${visible.length} phòng phù hợp trên tầng ${currentFloor}; ${visible.filter(available).length} phòng có thể đặt theo ngày đã chọn. Tổng số tầng: ${floors.length}.`}</p>
 {!validDates&&<p className="hr-muted">Vui lòng chọn ngày nhận phòng từ hôm nay trở đi và ngày trả sau ngày nhận để xác minh tình trạng phòng.</p>}
 {visible.length===0&&matchingType.length>0&&<p className="hr-muted" role="alert">Tầng này có {matchingType.length} phòng thuộc loại đã chọn, nhưng giá phòng cao hơn mức lọc {money(effectiveMaxPrice)}. Hãy kéo thanh giá sang phải để xem phòng.</p>}
 {visible.length===0&&floorRooms.length>0&&matchingType.length===0&&<p className="hr-muted" role="alert">Tầng này có {floorRooms.length} phòng, nhưng không thuộc loại phòng đang lọc. Hãy chọn “Tất cả loại phòng”.</p>}
 {visible.length>0?<div className="hr-floor-building"><div className="hr-floor-row">{visible.slice(0,Math.ceil(visible.length/2)).map(r=><button key={r.id} className={`hr-floor-room hr-room-shape-${typeIndex(r)} ${statusClass(r)} ${chosen.some(x=>x.id===r.id)?'selected':''}`} title={`${r.tenLoaiPhong} · ${status(r)}`} disabled={!available(r)} onClick={()=>toggle(r)}><strong>{r.soPhong}</strong><small>{r.tenLoaiPhong}</small><small>{money(Number(r.giaMoiDem))}</small><span className="hr-floor-door"/></button>)}</div><div className="hr-floor-corridor"><span>Hành lang</span><div className="hr-floor-lift">⇧⇩<small>Thang máy</small></div></div><div className="hr-floor-row bottom">{visible.slice(Math.ceil(visible.length/2)).map(r=><button key={r.id} className={`hr-floor-room hr-room-shape-${typeIndex(r)} ${statusClass(r)} ${chosen.some(x=>x.id===r.id)?'selected':''}`} title={`${r.tenLoaiPhong} · ${status(r)}`} disabled={!available(r)} onClick={()=>toggle(r)}><strong>{r.soPhong}</strong><small>{r.tenLoaiPhong}</small><small>{money(Number(r.giaMoiDem))}</small><span className="hr-floor-door"/></button>)}</div></div>:<p>Không có phòng phù hợp tại tầng này.</p>}
 </section><div className="hr-map-footer"><div><b>Chú thích loại phòng</b><div className="hr-type-legend">{types.map(([typeId,name],index)=><span key={typeId}><i className={`hr-shape-key hr-room-shape-${index%4}`}/>{name}</span>)}</div><b>Chú thích trạng thái phòng</b><p><span className="hr-swatch free"/> Phòng trống　<span className="hr-swatch booked"/> Đã đặt　<span className="hr-swatch maintenance"/> Đang bảo trì　<span className="hr-swatch unverified"/> Chưa xác minh</p></div><div><b>Hướng dẫn</b><p>① Chọn loại phòng và tầng (nếu cần)</p><p>② Nhấn vào phòng trống để xem thông tin</p><p>③ Chọn phòng và tiếp tục nhập thông tin khách hàng</p></div></div></main>
 <aside className="hr-card hr-map-cart"><div className="hr-cart-heading"><h2>Phòng đang chọn ({chosen.length} phòng)</h2><button onClick={()=>setChosen([])}>Xóa tất cả</button></div>{chosen.length===0?<p className="hr-muted">Chọn phòng còn trống trên sơ đồ để tiếp tục.</p>:chosen.map(r=><div className="hr-cart-room" key={r.id}>{r.hinhAnh&&<img src={r.hinhAnh} alt={r.tenLoaiPhong}/>}<div><strong>Phòng {r.soPhong}</strong><small>{r.tenLoaiPhong}</small><p>Tầng {r.tang}</p><b className="hr-red">{money(Number(r.giaMoiDem))}/đêm</b></div><button aria-label={`Bỏ phòng ${r.soPhong}`} onClick={()=>toggle(r)}>×</button></div>)}<hr/><h3>Tạm tính</h3>{chosen.map(r=><div className="hr-cart-price" key={r.id}><span>Phòng {r.soPhong} ({nights} đêm)</span><b>{money(Number(r.giaMoiDem)*nights)}</b></div>)}<div className="hr-cart-total"><b>Tổng tạm tính</b><strong className="hr-red">{money(total)}</strong></div>{chosen.length>0?<Link className="hr-primary" to={bookingLink()}>Tiếp tục →</Link>:<button className="hr-primary" disabled>Chọn phòng để tiếp tục</button>}<p className="hr-muted">Các phòng đã chọn được giữ khi Booking Service tạo đặt phòng thành công. Vui lòng hoàn tất thanh toán trong thời hạn hệ thống quy định.</p></aside></div></div></div>
}
