import { Star } from 'lucide-react'
import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { bookingApi,paymentApi,reviewApi,flightApi,type ReviewItem } from '../../api/services'
import type { Booking,Payment } from '../../types'

export default function MyReviewsPage(){
 type TypedReview = ReviewItem & { serviceType: 'HOTEL'|'ATTRACTION'|'FLIGHT' }
 const [tab,setTab]=useState<'pending'|'done'>('pending'),[bookings,setBookings]=useState<Booking[]>([]),[payments,setPayments]=useState<Payment[]>([]),[reviews,setReviews]=useState<TypedReview[]>([]),[endedFlights,setEndedFlights]=useState<Set<number>>(new Set())
 useEffect(()=>{Promise.all([bookingApi.mine(),paymentApi.mine(),reviewApi.hotelMine().catch(()=>[]),reviewApi.attractionMine().catch(()=>[]),reviewApi.flightMine().catch(()=>[])]).then(async([b,p,h,a,f])=>{setBookings(b);setPayments(p);setReviews([...h.map(x=>({...x,serviceType:'HOTEL' as const})),...a.map(x=>({...x,serviceType:'ATTRACTION' as const})),...f.map(x=>({...x,serviceType:'FLIGHT' as const}))]);const ids=[...new Set(b.flatMap(x=>x.danhSachDichVu.filter(i=>i.loaiDichVu==='FLIGHT').map(i=>i.dichVuId)))];const ended=new Set<number>();await Promise.all(ids.map(id=>flightApi.detail(id).then(x=>{if(new Date(x.thoiGianDen).getTime()<=Date.now())ended.add(id)}).catch(()=>{})));setEndedFlights(ended)})},[])
 const paid=new Set(payments.filter(p=>p.trangThai==='SUCCESS').map(p=>p.bookingId)), reviewed=new Set(reviews.map(r=>`${r.serviceType}:${r.bookingId}`))
 const pending=useMemo(()=>bookings.filter(b=>paid.has(b.id)&&b.danhSachDichVu.some(i=>!reviewed.has(`${i.loaiDichVu}:${b.id}`)&&(()=>{if(i.loaiDichVu==='FLIGHT')return endedFlights.has(i.dichVuId);if(i.loaiDichVu==='HOTEL'&&i.ngayKetThuc)return Date.now()>=new Date(`${i.ngayKetThuc}T00:00:00`).getTime();if(i.loaiDichVu==='ATTRACTION'&&i.ngayBatDau)return Date.now()>new Date(`${i.ngayBatDau}T23:59:59`).getTime();return false})())), [bookings,payments,reviews,endedFlights])
 return <div className="container customer-reviews-page"><div className="customer-my-promos-head"><div><span>ĐÁNH GIÁ</span><h1>Đánh giá của tôi</h1><p>Chỉ những dịch vụ đã sử dụng xong mới có thể đánh giá.</p></div></div>
 <div className="customer-my-promos-tabs"><button className={tab==='pending'?'active':''} onClick={()=>setTab('pending')}>Chưa đánh giá ({pending.length})</button><button className={tab==='done'?'active':''} onClick={()=>setTab('done')}>Đã đánh giá ({reviews.length})</button></div>
 <div className="customer-review-list">{tab==='pending'?(pending.length?pending.map(b=><article key={b.id}><div><b>{b.maBooking}</b><p>{b.danhSachDichVu.map(i=>i.loaiDichVu==='HOTEL'?'Khách sạn':i.loaiDichVu==='FLIGHT'?'Chuyến bay':'Địa điểm tham quan').join(' · ')}</p></div><Link to={`/bookings/${b.id}?review=1`}>Đánh giá ngay</Link></article>):<div className="customer-my-promos-empty"><Star/><h3>Không có dịch vụ chờ đánh giá</h3></div>):(reviews.length?reviews.map(x=><article key={`${x.targetId}-${x.id}`}><div><b>Đơn #{x.bookingId}</b><p className="review-stars">{'★'.repeat(x.soSao)}{'☆'.repeat(5-x.soSao)}</p><p>{x.noiDung||'Không có nhận xét.'}</p></div><small>{x.ngayTao?new Date(x.ngayTao).toLocaleString('vi-VN'):''}</small></article>):<div className="customer-my-promos-empty"><Star/><h3>Bạn chưa gửi đánh giá nào</h3></div>)}</div></div>
}
