spring.application.name=promotion-service
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/promotion_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=TakivivuAuthSecretKeyForJwtMustBeAtLeast32CharactersLong2026
promotion.internal-token=TAKIVIVU_PROMOTION_INTERNAL_2026

service.flight.url=http://localhost:8082
service.hotel.url=http://localhost:8083
service.attraction.url=http://localhost:8084

service.auth.url=http://localhost:8081
auth.internal-token=TAKIVIVU_AUTH_INTERNAL_2026
