spring.application.name=payment-service
server.port=8086

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

# DEV: cho Hibernate tự tạo/cập nhật bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# JWT
# =========================
app.jwt.secret=TakivivuAuthSecretKeyForJwtMustBeAtLeast32CharactersLong2026

# =========================
# BOOKING SERVICE
# =========================
service.booking.url=http://localhost:8085
service.booking.internal-token=TAKIVIVU_BOOKING_INTERNAL_2026

# =========================
# NOTIFICATION SERVICE
# =========================
service.notification.url=http://localhost:8089
notification.internal-token=TAKIVIVU_NOTIFICATION_INTERNAL_2026

# =========================
# BANK ACCOUNT
# =========================
payment.bank.id=${PAYMENT_BANK_ID:MB}
payment.bank.name=${PAYMENT_BANK_NAME:MB Bank}
payment.bank.account-number=${PAYMENT_BANK_ACCOUNT_NUMBER:0123456789}
payment.bank.account-name=${PAYMENT_BANK_ACCOUNT_NAME:TAKIVIVU}

# =========================
# VIETQR
# =========================
payment.vietqr.base-url=https://img.vietqr.io/image
payment.vietqr.template=compact2

# =========================
# SEPAY
# =========================
payment.sepay.webhook-secret=${SEPAY_WEBHOOK_SECRET:TAKIVIVU_SEPAY_SECRET_2026}

# =========================
# PAYPAL SANDBOX
# =========================
paypal.base-url=${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}

paypal.client-id=AalGKFzxBUunsoBTy1XewZCfxIHMKRb09IJtiyXSDEa4g_N3usofJvE9bQz37v_j3SW1NMqqruRWYeg_
paypal.client-secret=EHOFe-T38OiNXNuuTIMuSyPAMCpcmxmXEA3su133iEl10_j8w1biiCVBVRxkW8sX4I_73S_44Sx1NkQc

paypal.webhook-id=${PAYPAL_WEBHOOK_ID:07D93417BD692080A}

paypal.return-url=${PAYPAL_RETURN_URL:http://localhost:5173/payments/new}
paypal.cancel-url=${PAYPAL_CANCEL_URL:http://localhost:5173/payments/new}

paypal.currency=${PAYPAL_CURRENCY:USD}
paypal.vnd-per-usd=${PAYPAL_VND_PER_USD:25000}

# PayOS credentials and public URLs
payos.client-id=397d35ef-a0bc-4b40-893f-2c6b3712acf5
payos.api-key=ce462127-f897-4de0-8699-88801caa9a90
payos.checksum-key=31c6f10e56dae8d9609d6c213d89ec0bdf8849c681cfd80400fa7dc62f0851dd
payos.return-url=${PAYOS_RETURN_URL:http://localhost:5173/payments/new}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:5173/payments/new}

# =========================
# PAYPAL WEBHOOK
# =========================
# Sandbox webhook:
# https://guide-island-wallace-spirits.trycloudflare.com/api/payments/paypal/webhook
#
# Quick Tunnel URL có thể thay đổi khi cloudflared được chạy lại.
