package com.example.notificationservice.entity;

public enum NotificationType {

    REGISTER_SUCCESS,

    BOOKING_CREATED,

    PAYMENT_SUCCESS,

    PAYMENT_FAILED,

    BOOKING_CONFIRMED,

    BOOKING_CANCELLED,

    REFUND_SUCCESS,
    PROVIDER_CONFIRM_DEADLINE,
    PROVIDER_NEW_BOOKING,
    PROVIDER_BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    PAYMENT_TIMEOUT_REFUNDED,
    CANCEL_REQUESTED,
    CANCEL_REJECTED
}