import { ArrowLeft, Armchair, List, Plane, Users } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { flightApi } from '../../api/services'
import type { Flight, FlightInventory } from '../../types'
import { apiError } from '../../utils/format'

export default function ProviderFlightSeatsPage(){
  const {id}=useParams(); const flightId=Number(id)
  const [flight,setFlight]=useState<Flight|null>(null); const [inventory,setInventory]=useState<FlightInventory|null>(null)
  const [fare,setFare]=useState(''); const [tab,setTab]=useState<'map'|'list'>('map'); const [error,setError]=useState(''); const [selected,setSelected]=useState<FlightInventory['seats'][number]|null>(null)
  useEffect(()=>{Promise.all([flightApi.detail(flightId),flightApi.inventory(flightId)]).then(([f,i])=>{setFlight(f);setInventory(i)}).catch(e=>setError(apiError(e)))},[flightId])
  const seats=useMemo(()=>inventory?.seats.filter(s=>!fare||s.hangVe===fare)||[],[inventory,fare])
  const rows=useMemo(()=>{const m=new Map<number,typeof seats>();seats.forEach(s=>{const n=parseInt(s.maGhe,10);if(!Number.isNaN(n))m.set(n,[...(m.get(n)||[]),s])});return [...m.entries()].sort((a,b)=>a[0]-b[0])},[seats])
  if(error)return <div className="flight-seat-error">{error}</div>; if(!flight||!inventory)return <div>Đang tải sơ đồ ghế...</div>
  return <div className="provider-seat-page">
    <div className="provider-seat-heading"><Link to="/provider/flights"><ArrowLeft/>Quay lại</Link><div><h1>Sơ đồ ghế - Chuyến bay {flight.maChuyenBay}</h1><p>{flight.diemDi} ({flight.sanBayDi.split(' ')[0]}) → {flight.diemDen} ({flight.sanBayDen.split(' ')[0]}) &nbsp;|&nbsp; {new Date(flight.thoiGianKhoiHanh).toLocaleDateString('vi-VN')} &nbsp;|&nbsp; {new Date(flight.thoiGianKhoiHanh).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})} - {new Date(flight.thoiGianDen).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</p></div></div>
    <div className="provider-seat-layout">
      <aside><div className="seat-side-card"><h2>Thông tin chuyến bay</h2><dl><div><dt>Hãng hàng không</dt><dd>{flight.hangHangKhong}</dd></div><div><dt>Mã chuyến bay</dt><dd>{flight.maChuyenBay}</dd></div><div><dt>Tuyến bay</dt><dd>{flight.diemDi} → {flight.diemDen}</dd></div><div><dt>Ngày bay</dt><dd>{new Date(flight.thoiGianKhoiHanh).toLocaleDateString('vi-VN')}</dd></div><div><dt>Giờ khởi hành</dt><dd>{new Date(flight.thoiGianKhoiHanh).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt>Giờ đến</dt><dd>{new Date(flight.thoiGianDen).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt>Tổng số ghế</dt><dd>{flight.tongSoGhe}</dd></div></dl></div><div className="seat-side-card"><h2>Chọn hạng vé</h2><label><input type="radio" checked={!fare} onChange={()=>setFare('')}/> Tất cả hạng vé</label>{inventory.fares.map(f=><label key={f.id}><input type="radio" checked={fare===f.hangVe} onChange={()=>setFare(f.hangVe)}/>{f.hangVe}<span>{f.soGhe} ghế</span></label>)}</div></aside>
      <main className="aircraft-card"><div className="seat-tabs"><button className={tab==='map'?'active':''} onClick={()=>setTab('map')}><Plane/>Sơ đồ ghế</button><button className={tab==='list'?'active':''} onClick={()=>setTab('list')}><List/>Danh sách ghế</button></div>{tab==='map'?<div className="aircraft-wrap"><div className="aircraft-wing left"/><div className="aircraft-wing right"/><div className="aircraft-body"><div className="aircraft-cockpit"><span/><span/></div><div className="aircraft-facilities"><b>🚻</b><b>☕</b></div><div className="seat-columns"><span>A</span><span>B</span><span>C</span><i/><span>D</span><span>E</span><span>F</span></div>{rows.map(([row,rs])=><div className="seat-row" key={row}><b>{row}</b>{['A','B','C'].map(c=><Seat key={c} seat={rs.find(s=>s.maGhe===`${row}${c}`)} selected={selected?.id===rs.find(s=>s.maGhe===`${row}${c}`)?.id} onSelect={setSelected}/>)}<i/>{['D','E','F'].map(c=><Seat key={c} seat={rs.find(s=>s.maGhe===`${row}${c}`)} selected={selected?.id===rs.find(s=>s.maGhe===`${row}${c}`)?.id} onSelect={setSelected}/>)}</div>)}<div className="aircraft-tail-facilities"><b>🚻</b><b>☕</b></div><span className="aircraft-exit exit-left"/><span className="aircraft-exit exit-right"/></div></div>:<div className="seat-list">{seats.map(s=><div key={s.id}><Armchair/><b>{s.maGhe}</b><span>{s.hangVe}</span><em className={s.trangThai.toLowerCase()}>{s.trangThai==='AVAILABLE'?'Ghế trống':'Đã đặt'}</em></div>)}</div>}</main>
      <aside><div className="seat-side-card"><h2>Chú thích</h2><div className="seat-legend"><p><i className="available"/>Ghế trống</p><p><i className="selected"/>Ghế đang chọn</p><p><i className="booked"/>Ghế đã đặt</p><p><i className="facility">🚻</i>Nhà vệ sinh</p><p><i className="facility">☕</i>Khu vực bếp</p><p><i className="exit"/>Cửa thoát hiểm</p></div></div>{selected&&<div className="seat-side-card selected-seat-card"><h2>Thông tin ghế đang chọn</h2><dl><div><dt>Mã ghế</dt><dd>{selected.maGhe}</dd></div><div><dt>Hạng vé</dt><dd>{selected.hangVe}</dd></div><div><dt>Trạng thái</dt><dd>{selected.trangThai==='AVAILABLE'?'Ghế trống':'Đã đặt'}</dd></div><div><dt>Giá vé</dt><dd>{Number(inventory.fares.find(f=>f.hangVe===selected.hangVe)?.giaVe||0).toLocaleString('vi-VN')} đ</dd></div></dl><button disabled={selected.trangThai!=='AVAILABLE'}>Chọn ghế này</button></div>}</aside>
    </div>
  </div>
}
function Seat({seat,selected,onSelect}:{seat?:FlightInventory['seats'][number],selected?:boolean,onSelect:(s:FlightInventory['seats'][number])=>void}){return seat?<button type="button" title={`${seat.maGhe} · ${seat.hangVe}`} onClick={()=>seat.trangThai==='AVAILABLE'&&onSelect(seat)} className={`plane-seat ${seat.trangThai==='AVAILABLE'?'available':'booked'} ${selected?'selected':''}`}>{seat.trangThai==='AVAILABLE'?'': '×'}</button>:<span className="plane-seat missing"/>}
